spring.application.name=ChatMemory
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
server.port=8090
logging.level.org.springframework.ai.chat.client.advisor=DEBUG